import { writeFileSync, mkdirSync, copyFileSync } from 'node:fs';

const root = new URL('.', import.meta.url);
const pages = ['Home', 'About', 'Experience', 'Projects', 'Skills', 'Education', 'Contact'];
const files = pages.map((p, i) => i ? `${p.toLowerCase()}.html` : 'index.html');
const external = (url, label, cls = '') => `<a ${cls ? `class="${cls}" ` : ''}href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`;
const local = (file, label, cls = '') => `<a ${cls ? `class="${cls}" ` : ''}href="${file}"${file === 'index.html' ? '' : ' target="_blank" rel="noopener noreferrer"'}>${label}</a>`;
const github = 'https://github.com/danishcorder';
const linkedin = 'https://www.linkedin.com/in/muhammad-danish-0b3727376';
const base = 'https://muhammaddanish-sage.vercel.app/';
const portrait = 'assets/images/profile.jpg';

function shell(name, description, body) {
  const file = files[pages.indexOf(name)];
  const title = name === 'Home' ? 'Muhammad Danish | Data Analyst & Machine Learning Developer' : `${name} | Muhammad Danish`;
  const nav = pages.map((p, i) => `<a href="${files[i]}"${i ? ' target="_blank" rel="noopener noreferrer"' : ''}${p === name ? ' aria-current="page"' : ''}>${p}</a>`).join('');
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#07111f"><meta name="description" content="${description}">
<meta name="author" content="Muhammad Danish"><link rel="canonical" href="${base}${file === 'index.html' ? '' : file}">
<meta property="og:type" content="website"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${base}${file === 'index.html' ? '' : file}"><meta property="og:image" content="${base}${portrait}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${description}"><meta name="twitter:image" content="${base}${portrait}">
<title>${title}</title><link rel="stylesheet" href="style.css"><script defer src="script.js"></script>
<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Person',name:'Muhammad Danish',url:base,image:base+portrait,jobTitle:'Data Analyst and Machine Learning Developer',alumniOf:{'@type':'CollegeOrUniversity',name:'Bahauddin Zakariya University'},sameAs:[github,linkedin],knowsAbout:['Data Analytics','Machine Learning','Python Automation','Mathematics']})}</script>
</head><body data-page="${name.toLowerCase()}"><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="nav-shell"><a class="brand" href="index.html" aria-label="Muhammad Danish home"><span class="brand-mark">MD</span><span>Muhammad Danish</span></a><nav id="site-nav" class="nav-links" aria-label="Primary navigation">${nav}</nav><div class="nav-actions"><button class="theme-toggle" type="button" aria-label="Switch to light theme" title="Toggle color theme">◐</button><button class="nav-toggle" type="button" aria-controls="site-nav" aria-expanded="false" aria-label="Open menu"><span aria-hidden="true">☰</span></button></div></div></header>
<main id="main">${body}</main><footer class="site-footer"><div class="wrap footer-inner"><div><strong>Muhammad Danish</strong><p>Data • Machine Learning • Python Automation</p></div><div class="footer-links">${local('projects.html','Projects')}${local('contact.html','Contact')}${external(github,'GitHub')}</div><small>© <span id="current-year"></span> Muhammad Danish</small></div></footer></body></html>`;
}
const eyebrow = text => `<p class="eyebrow">${text}</p>`;
const heading = (label, title, intro='') => `<div class="page-heading">${eyebrow(label)}<h1>${title}</h1>${intro ? `<p class="lede">${intro}</p>` : ''}</div>`;
const section = (title, body, cls='') => `<section class="section ${cls}"><h2>${title}</h2>${body}</section>`;
const btn = (href, label, primary=false, isExternal=false) => isExternal ? external(href,label,`btn ${primary?'btn-primary':'btn-secondary'}`) : local(href,label,`btn ${primary?'btn-primary':'btn-secondary'}`);

const home = () => `<section class="home-hero wrap"><div class="hero-copy">${eyebrow('BS MATHEMATICS  /  DATA  /  AI  /  AUTOMATION')}<h1>Muhammad Danish<span>Data Analyst · Machine Learning Developer · Python Automation</span></h1><p class="lede">I combine mathematics, data, machine learning, and software development to build practical systems for real-world problems.</p><div class="actions">${btn('projects.html','Explore Projects',true)}${btn(github,'GitHub ↗',false,true)}${btn(linkedin,'LinkedIn ↗',false,true)}${btn('contact.html','Contact Me')}</div><div class="hero-note"><span class="status-dot"></span> Open to data, AI/ML, and Python opportunities</div></div><div class="hero-portrait"><img src="${portrait}" width="640" height="640" alt="Portrait of Muhammad Danish" fetchpriority="high"><div class="portrait-caption"><strong>Mathematics × technology</strong><span>Practical work, clear thinking, measurable value.</span></div></div></section>
<section class="wrap section intro-section"><div class="section-heading">${eyebrow('SELECTED WORK')}<h2>Built around real problems.</h2><p>Industrial workflows, quality monitoring, machine learning education, and forecasting.</p></div><div class="featured-grid">${['msm','texgauge','atlas'].map(id=>featured(projects.find(p=>p.id===id))).join('')}</div><div class="section-end">${btn('projects.html','See all projects →')}</div></section>
<section class="wrap section split-cta"><div>${eyebrow('BACKGROUND')}<h2>Quantitative thinking, applied in the field.</h2><p>I study Mathematics at Bahauddin Zakariya University and have explored production processes, data quality, forecasting, and digital workflows through industrial work.</p></div><div class="actions">${btn('about.html','About me',true)}${btn('experience.html','Experience')}</div></section>`;

const about = `${heading('ABOUT','A mathematical foundation for useful technology.','I work where analytical thinking meets practical systems: data, machine learning, AI, Python automation, and industrial software.')}<div class="wrap about-layout"><img class="about-photo" src="${portrait}" width="640" height="640" alt="Muhammad Danish" loading="lazy"><div><h2>Professional direction</h2><p>I am a BS Mathematics student at Bahauddin Zakariya University. I am interested in using statistics, mathematical modelling, and software to make data easier to understand and operations easier to manage.</p><p>My recent work spans textile quality monitoring, material requisition workflows, production forecasting, ML learning tools, and database-backed applications. Web development supports those systems; my main focus is data, AI/ML, and Python.</p><div class="actions">${btn('projects.html','Explore projects',true)}${btn('contact.html','Get in touch')}</div></div></div>${section('Professional snapshot',`<dl class="snapshot-grid"><div><dt>Degree</dt><dd>BS Mathematics</dd></div><div><dt>Focus</dt><dd>Data Analytics · Machine Learning · Python Automation</dd></div><div><dt>Location</dt><dd>Punjab, Pakistan</dd></div><div><dt>Target roles</dt><dd>Data Analyst · AI/ML Intern · Python Developer</dd></div><div><dt>Interests</dt><dd>Industrial technology · forecasting · mathematical modelling</dd></div></dl>`,'wrap')}`;

const experience = `${heading('EXPERIENCE','Industrial context for better software.','Hands-on exposure to spinning operations, quality workflows, production data, and opportunities for digitization.')}<section class="wrap section"><article class="experience-card"><div class="experience-meta"><span class="pill">Industrial internship</span><span>Masood Spinning Mill / Mahmood Group</span></div><h2>Spinning operations, analytics & digitalization</h2><p>I studied how production and quality data moves through operational workflows, then explored practical ways to improve visibility and reduce manual work.</p><div class="experience-grid"><div><h3>Quality monitoring</h3><p>Developed TexGauge IQ concepts for sample weights, CV%, G/Y%, and Hank Roving quality checks.</p></div><div><h3>Production analysis</h3><p>Worked with production data and Python-based forecasting ideas for planning and trend review.</p></div><div><h3>Workflow digitization</h3><p>Examined material requisition and reporting processes and proposed more traceable digital workflows.</p></div><div><h3>Data quality</h3><p>Cleaned inventory and master data, including duplicate normalization, to improve operational records.</p></div></div></article></section><section class="wrap section split-cta"><div><h2>From observation to prototypes.</h2><p>The industrial problems I encountered shaped several of my strongest projects.</p></div>${btn('projects.html','See related projects',true)}</section>`;

const projects = [
{id:'msm',title:'MSM Digital Material Requisition Intelligence System',category:'Industrial analytics · In development',problem:'Manual material requests can be difficult to trace and plan.',solution:'A digital requisition workflow with analytics and decision-support concepts.',features:'Demand forecasting · anomaly detection · delay prediction · request tracking',tech:'Python · SQL · Machine Learning · Analytics',value:'A clearer view of requests, inventory, and planning. The intelligence features are in development.',links:[['contact.html','Discuss project',false]]},
{id:'texgauge',title:'TexGauge IQ — Smart Textile Quality Monitoring',category:'Industrial quality · Prototype',problem:'Sample readings are harder to interpret when recorded across separate manual steps.',solution:'A quality dashboard concept for spinning processes and pass/fail review.',features:'Sample weight · CV% · G/Y% · Hank Roving · status checks',tech:'Python · FastAPI · WebSocket · PySerial · Statistics',value:'Makes quality signals easier to review in one workflow.',links:[['https://danishcorder.github.io/TexGuage/index.html','Live demo ↗',true]]},
{id:'atlas',title:'Machine Learning Atlas',category:'ML education · Live',problem:'Machine learning concepts can be abstract and difficult to compare.',solution:'A visual learning platform with organized model pages and interactive explanations.',features:'Concept guides · model comparisons · datasets · visual learning',tech:'Machine Learning · JavaScript · Data Visualization',value:'A more approachable route into ML concepts.',links:[['https://danishcorder.github.io/machine-learning-atlas/','Live site ↗',true],['https://github.com/danishcorder/machine-learning-atlas','Repository ↗',true]]},
{id:'forecast',title:'Production Forecasting System',category:'Data science · Case study',problem:'Production planning needs a useful view of trends and expected output.',solution:'A Python workflow for exploring historical production data and forecasts.',features:'Daily · weekly · monthly views · trend analysis · forecast plots',tech:'Python · Pandas · Matplotlib · Forecasting · EDA',value:'Supports data-informed planning conversations.',links:[]},
{id:'water',title:'Water Delivery Management System',category:'Operations software · Concept',problem:'Deliveries, bottle balances, billing, and routes create fragmented records.',solution:'A multi-role platform concept for admins, riders, and customers.',features:'Delivery records · billing · bottle tracking · reporting · routes',tech:'Dashboard design · Workflow · Mobile UX · Operations',value:'A clearer operational picture across the delivery cycle.',links:[['contact.html','Request walkthrough',false]]},
{id:'assistant',title:'AI Portfolio Assistant',category:'Interactive portfolio · Live',problem:'Recruiters may want direct answers instead of scanning a long portfolio.',solution:'A conversational interface for exploring my background and work.',features:'Questions about projects · skills · education · experience · goals',tech:'AI · JavaScript · Conversational UX',value:'Helps visitors find relevant information quickly.',links:[['https://danishcorder.github.io/Muhammad-danish-AI-Assiatant/','Open assistant ↗',true]]}
];
function featured(p){return `<article class="featured-card"><img src="assets/images/${p.id}.svg" width="960" height="540" alt="Illustrated ${p.title} interface" loading="lazy"><div class="featured-body"><span class="eyebrow">${p.category}</span><h3>${p.title}</h3><p>${p.solution}</p>${local('projects.html', 'View project details →')}</div></article>`}
function projectCard(p){return `<article class="project-card" id="${p.id}"><img src="assets/images/${p.id}.svg" width="960" height="540" alt="Illustrated ${p.title} interface" loading="lazy"><div class="project-content"><p class="eyebrow">${p.category}</p><h2>${p.title}</h2><div class="project-facts"><p><strong>Problem</strong>${p.problem}</p><p><strong>Solution</strong>${p.solution}</p><p><strong>Key features</strong>${p.features}</p><p><strong>Technology</strong>${p.tech}</p><p><strong>Value</strong>${p.value}</p></div><div class="project-links">${p.links.map(([href,label,ext])=>ext?external(href,label):local(href,label)).join('')}</div></div></article>`}
const projectPage = `${heading('PROJECTS','Applied work, clearly explained.','A selection of industrial, data, ML, and software projects. Visuals are illustrative interface concepts where a product screenshot is unavailable.')}<div class="wrap project-grid">${projects.map(projectCard).join('')}</div>`;
const groups=[['Data & Analytics','Python · Pandas · NumPy · SQL · Excel · Data cleaning · EDA · Visualization','Cleaning, exploring, and communicating data for decisions.'],['Machine Learning','Regression · Classification · Forecasting · Feature engineering · Evaluation · Anomaly detection concepts','Building and evaluating models with practical context.'],['Backend & Automation','FastAPI · Flask · REST APIs · WebSocket · PySerial · PyInstaller · Python automation','Connecting data, devices, and workflows.'],['Web Development','HTML · CSS · JavaScript · Responsive design','Building accessible interfaces for useful tools.'],['Mathematics','Statistics · Linear algebra · Calculus · Mathematical modelling · Problem solving','The quantitative foundation behind my work.'],['Tools & Workflow','Git · GitHub · Excel · MS Office · AI-assisted development','Organizing implementation, analysis, and collaboration.']];
const skills=`${heading('SKILLS','Tools grouped by the problems I solve.','A practical toolkit spanning quantitative analysis, machine learning, automation, and product development.')}<section class="wrap section skill-list">${groups.map(([title,items,desc],i)=>`<article class="skill-row"><span class="skill-number">0${i+1}</span><div><h2>${title}</h2><p>${desc}</p></div><p class="skill-items">${items}</p></article>`).join('')}</section>`;
const education=`${heading('EDUCATION','Mathematics, applied with purpose.','A strong quantitative base supports my work in data analytics, machine learning, and software.')}<section class="wrap section education-layout"><article class="education-card"><span class="eyebrow">2023–2027</span><h2>BS Mathematics</h2><p class="institution">Bahauddin Zakariya University</p><p>Core areas include statistics, linear algebra, calculus, numerical methods, and mathematical modelling.</p></article><article class="education-card"><span class="eyebrow">RECOGNITION</span><h2>HEC Need-Based Scholarship</h2><p>Recipient of the Higher Education Commission need-based scholarship during undergraduate study.</p></article></section>`;
const contact=`${heading('CONTACT','Let’s talk about useful work.','Interested in working together, discussing a project, or exploring an opportunity? Feel free to get in touch.')}<section class="wrap section contact-layout"><div class="contact-primary"><h2>Start a conversation.</h2><p>For data analytics, AI/ML, Python development, automation, or related opportunities, email is the best way to reach me.</p><a class="btn btn-primary" href="mailto:muhammaddanish2327@gmail.com">Email Muhammad ↗</a></div><div class="contact-list"><a href="mailto:muhammaddanish2327@gmail.com"><span>Email</span><strong>muhammaddanish2327@gmail.com</strong><span aria-hidden="true">↗</span></a>${external(github,'<span>GitHub</span><strong>github.com/danishcorder</strong><span aria-hidden="true">↗</span>')}${external(linkedin,'<span>LinkedIn</span><strong>Muhammad Danish</strong><span aria-hidden="true">↗</span>')}${external(base,'<span>Portfolio</span><strong>muhammaddanish-sage.vercel.app</strong><span aria-hidden="true">↗</span>')}</div></section>`;

const content={Home:[home(),'Muhammad Danish is a BS Mathematics student focused on Data Analytics, Machine Learning, Python Automation, AI and practical software.'],About:[about,'About Muhammad Danish: BS Mathematics student working in data analytics, machine learning, industrial technology, and Python automation.'],Experience:[experience,'Industrial internship experience at Masood Spinning Mill and Mahmood Group, including quality monitoring, forecasting and digitization.'],Projects:[projectPage,'Explore Muhammad Danish’s projects in data analytics, machine learning, industrial software, forecasting, and AI.'],Skills:[skills,'Skills in Python, SQL, data analytics, machine learning, automation, web development, and mathematics.'],Education:[education,'BS Mathematics at Bahauddin Zakariya University and HEC Need-Based Scholarship.'],Contact:[contact,'Contact Muhammad Danish for data analytics, AI/ML, Python development and automation opportunities.']};
for(const [name,[body,desc]] of Object.entries(content)) writeFileSync(new URL(files[pages.indexOf(name)],root),shell(name,desc,body));
mkdirSync(new URL('assets/images/',root),{recursive:true});
copyFileSync(new URL('New folder/danish.jpg',root),new URL('assets/images/profile.jpg',root));

// Lightweight project-specific interface illustrations. These depict concepts, not product screenshots.
const visuals={
msm:{tag:'REQUISITION INTELLIGENCE',title:'Material request overview',labels:['Open requests','Inventory status','Forecast'],chart:'M10 110 L75 88 L135 95 L195 60 L255 76 L315 40 L375 52',accent:'#3b82f6'},
texgauge:{tag:'TEXTILE QUALITY',title:'TexGauge IQ',labels:['Sample weight','CV% / G/Y%','PASS'],chart:'M10 93 L75 98 L135 62 L195 73 L255 47 L315 58 L375 35',accent:'#06b6d4'},
atlas:{tag:'MACHINE LEARNING ATLAS',title:'Explore model families',labels:['Regression','Classification','Evaluation'],chart:'M10 113 C80 100 115 45 180 65 S280 92 375 28',accent:'#60a5fa'},
forecast:{tag:'PRODUCTION FORECAST',title:'Output trend and projection',labels:['Historical','Predicted','Planning'],chart:'M10 108 L65 98 L120 89 L175 80 L230 63 L285 57 L335 40 L375 25',accent:'#38bdf8'},
water:{tag:'WATER DELIVERY',title:'Operations dashboard',labels:['Deliveries','Bottle balance','Routes'],chart:'M10 100 L65 100 L65 78 L120 78 L120 62 L175 62 L175 46 L230 46 L230 30 L285 30 L285 20 L375 20',accent:'#22c55e'},
assistant:{tag:'AI PORTFOLIO ASSISTANT',title:'Ask about my work',labels:['Projects','Skills','Experience'],chart:'M10 98 L80 98 L80 72 L185 72 L185 42 L310 42 L310 24 L375 24',accent:'#818cf8'}
};
for(const [id,v] of Object.entries(visuals)) {
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 540" role="img" aria-label="${v.title} interface illustration"><defs><linearGradient id="bg" x2="1" y2="1"><stop stop-color="#0b1a2b"/><stop offset="1" stop-color="#132e49"/></linearGradient></defs><rect width="960" height="540" rx="24" fill="url(#bg)"/><rect x="26" y="25" width="908" height="490" rx="17" fill="#0d2033" stroke="#2a4962"/><rect x="26" y="25" width="908" height="52" rx="17" fill="#142b43"/><circle cx="57" cy="51" r="6" fill="#46708c"/><circle cx="78" cy="51" r="6" fill="#46708c"/><circle cx="99" cy="51" r="6" fill="#46708c"/><text x="47" y="121" fill="${v.accent}" font-family="Arial,sans-serif" font-size="16" font-weight="700" letter-spacing="3">${v.tag}</text><text x="47" y="163" fill="#f8fafc" font-family="Arial,sans-serif" font-size="32" font-weight="700">${v.title}</text><rect x="47" y="195" width="535" height="275" rx="15" fill="#10283f" stroke="#2b4860"/><text x="73" y="230" fill="#9fb5cb" font-family="Arial,sans-serif" font-size="16">Activity &amp; trends</text><path d="M73 420 H548 M73 365 H548 M73 310 H548 M73 255 H548" stroke="#244057" stroke-width="2"/><path d="${v.chart}" transform="translate(65 278) scale(1.23 1.18)" fill="none" stroke="${v.accent}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><rect x="605" y="195" width="308" height="80" rx="13" fill="#17354c"/><rect x="605" y="292" width="308" height="80" rx="13" fill="#17354c"/><rect x="605" y="389" width="308" height="80" rx="13" fill="#17354c"/>${v.labels.map((x,i)=>`<circle cx="630" cy="${235+i*97}" r="7" fill="${v.accent}"/><text x="650" y="${242+i*97}" fill="#e8f1f9" font-family="Arial,sans-serif" font-size="18" font-weight="600">${x}</text>`).join('')}</svg>`;
 writeFileSync(new URL(`assets/images/${id}.svg`,root),svg);
}

